# Generated by Django 4.1.7 on 2023-05-19 15:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Электронная почта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер')),
                ('surname', models.CharField(max_length=100, verbose_name='Имя, Фамилия')),
                ('is_staff', models.BooleanField(default=False, verbose_name='персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Админ')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('reset_password_code', models.CharField(blank=True, editable=False, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
